version: CI-{build}
image: Ubuntu2204
branches:
  only:
  - main
install:
- sh: >-
    sudo apt update -qq

    sudo apt install -qqy -o DPkg::Progress-Fancy=0 --no-install-recommends libsdl2-dev libssl-dev

    git submodule update --init -recursive
build_script:
- sh: make
test_script:
- sh: >-
    mkdir aptyrian

    mkdir aptyrian/apdata

    cp opentyrian aptyrian/aptyrian

    cp COPYING aptyrian/

    cp apdata/* aptyrian/apdata/

    7za a "aptyrian-Linux-Release.zip" "aptyrian"
artifacts:
- path: '*.zip'

